(()=>{
'use strict';
const D=window.RICE_LINEAGE_DATA;if(!D)return;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const byId=new Map(D.nodes.map(n=>[n.id,n]));
const parentEvents=new Map(),childEvents=new Map();
D.nodes.forEach(n=>{parentEvents.set(n.id,[]);childEvents.set(n.id,[])});
D.events.forEach(e=>{childEvents.get(e.child)?.push(e);e.parents.forEach(p=>parentEvents.get(p)?.push(e))});
let selected=new URLSearchParams(location.search).get('rice');if(!byId.has(selected))selected=D.defaultRice;
let lang=localStorage.getItem('rice-lineage-lang')||'ja';
const text=(n,k='summary')=>n[k]?.[lang]||n[k]?.ja||'';
const parentsOf=id=>[...new Set((childEvents.get(id)||[]).flatMap(e=>e.parents))];
const childrenOf=id=>[...new Set((parentEvents.get(id)||[]).map(e=>e.child))];
const walk=(id,next)=>{const seen=new Set(),stack=[id];while(stack.length){const x=stack.pop();for(const y of next(x)){if(y!==id&&!seen.has(y)){seen.add(y);stack.push(y)}}}return seen};
const relatedState=id=>{const p=new Set(parentsOf(selected)),c=new Set(childrenOf(selected));if(id===selected)return'selected';if(p.has(id)||c.has(id))return'direct';const a=walk(selected,parentsOf),d=walk(selected,childrenOf);if(a.has(id)||d.has(id))return'related';return'unrelated'};
function coContext(){const s=new Set([selected,...parentsOf(selected),...childrenOf(selected)]);D.events.forEach(e=>{if(e.child===selected||e.parents.includes(selected)||childrenOf(selected).includes(e.child)){e.parents.forEach(p=>s.add(p));s.add(e.child)}});return s}
function setSelected(id,{scroll=false,history=true,close=false}={}){if(!byId.has(id))return;selected=id;if(history){const u=new URL(location.href);u.searchParams.set('rice',id);historyReplace(u)}renderAll();if(scroll)$('#lineage')?.scrollIntoView({behavior:'smooth',block:'start'});if(close)closeFullMap()}
function historyReplace(u){try{history.replaceState({},'',u)}catch{}}
function svgEl(tag,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function curve(x1,y1,x2,y2){const m=(x1+x2)/2;return`M${x1} ${y1} C${m} ${y1},${m} ${y2},${x2} ${y2}`}
function renderGraph(svg){if(!svg)return;svg.innerHTML='';const vp=svgEl('g',{class:'graph-viewport'});svg.append(vp);const context=coContext(),directParents=new Set(parentsOf(selected)),directChildren=new Set(childrenOf(selected));
D.events.forEach(e=>{const child=byId.get(e.child),ps=e.parents.map(byId.get).filter(Boolean);if(!child||!ps.length)return;const active=e.child===selected||e.parents.includes(selected)||walk(selected,parentsOf).has(e.child)||walk(selected,childrenOf).has(e.child)||e.parents.some(p=>walk(selected,parentsOf).has(p)||walk(selected,childrenOf).has(p));const direct=e.child===selected||e.parents.includes(selected);const cls=`edge ${e.type==='MUTATION'?'mutation ':''}${direct?'direct':active?'related':''}`;
if(ps.length>1){const jx=Math.round((Math.max(...ps.map(p=>p.x))+child.x)/2),jy=child.y;ps.forEach(p=>vp.append(svgEl('path',{d:curve(p.x+76,p.y,jx,jy),class:cls,'data-event':e.id})));vp.append(svgEl('circle',{cx:jx,cy:jy,r:5,class:`junction ${direct?'related':active?'related':''}`}));vp.append(svgEl('path',{d:curve(jx,jy,child.x-76,child.y),class:cls,'data-event':e.id}));const label=svgEl('text',{x:jx,y:jy-11,class:'event-label','text-anchor':'middle'});label.textContent=e.type;vp.append(label)}else{const p=ps[0];vp.append(svgEl('path',{d:curve(p.x+76,p.y,child.x-76,child.y),class:cls,'data-event':e.id}));const label=svgEl('text',{x:(p.x+child.x)/2,y:(p.y+child.y)/2-8,class:'event-label','text-anchor':'middle'});label.textContent=e.type;vp.append(label)}});
D.nodes.forEach(n=>{let state=relatedState(n.id);if(context.has(n.id)&&state==='unrelated')state='related';const support=!n.featured||n.type==='support';const w=support?122:156,h=support?48:62;const g=svgEl('g',{class:`node ${state}${support?' support':''}`,transform:`translate(${n.x-w/2} ${n.y-h/2})`,role:'button',tabindex:'0','aria-label':`${n.ja} ${n.en}`,'data-id':n.id});const r=svgEl('rect',{class:'node-card',width:w,height:h,rx:support?7:9});g.append(r);const ja=svgEl('text',{class:'node-ja',x:12,y:support?21:27});ja.textContent=lang==='ja'?n.ja:n.en;g.append(ja);const en=svgEl('text',{class:'node-en',x:12,y:support?36:45});en.textContent=lang==='ja'?n.en:n.region;g.append(en);if(!support){const role=svgEl('text',{class:'node-role',x:w-10,y:13,'text-anchor':'end'});role.textContent=n.type==='landrace'?'ORIGIN':n.year||'';g.append(role)}g.addEventListener('click',ev=>{ev.stopPropagation();setSelected(n.id)});g.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();setSelected(n.id)}});vp.append(g)});
applyTransform(svg)}
const viewStates=new WeakMap();function stateFor(svg){if(!viewStates.has(svg))viewStates.set(svg,{scale:1,tx:0,ty:0});return viewStates.get(svg)}function applyTransform(svg){const g=$('.graph-viewport',svg);if(!g)return;const s=stateFor(svg);g.setAttribute('transform',`translate(${s.tx} ${s.ty}) scale(${s.scale})`)}function zoom(svg,f){const s=stateFor(svg);s.scale=Math.max(.55,Math.min(2.4,s.scale*f));applyTransform(svg)}function fit(svg){const s=stateFor(svg);s.scale=1;s.tx=0;s.ty=0;applyTransform(svg)}
function wirePanZoom(svg,{pinch=false}={}){if(!svg)return;let drag=null,pointers=new Map(),pinchStart=null;svg.addEventListener('pointerdown',e=>{if(e.target.closest?.('.node'))return;svg.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)drag={x:e.clientX,y:e.clientY,tx:stateFor(svg).tx,ty:stateFor(svg).ty};if(pinch&&pointers.size===2){const a=[...pointers.values()];pinchStart={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale:stateFor(svg).scale}}});svg.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size===2&&pinchStart){const a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);stateFor(svg).scale=Math.max(.55,Math.min(2.4,pinchStart.scale*dist/pinchStart.dist));applyTransform(svg);return}if(drag&&pointers.size===1){const s=stateFor(svg),scaleX=1840/svg.clientWidth,scaleY=980/svg.clientHeight;s.tx=drag.tx+(e.clientX-drag.x)*scaleX/s.scale;s.ty=drag.ty+(e.clientY-drag.y)*scaleY/s.scale;applyTransform(svg)}});const up=e=>{pointers.delete(e.pointerId);if(pointers.size<2)pinchStart=null;if(!pointers.size)drag=null};svg.addEventListener('pointerup',up);svg.addEventListener('pointercancel',up);svg.addEventListener('wheel',e=>{if(!(e.ctrlKey||e.metaKey))return;e.preventDefault();zoom(svg,e.deltaY<0?1.1:.9)},{passive:false})}
function nodeButton(id){const n=byId.get(id);if(!n)return'';return`<button class="family-node" data-mobile-select="${n.id}"><strong>${lang==='ja'?n.ja:n.en}</strong><small>${lang==='ja'?n.en:n.region}</small></button>`}
function sourcesFor(id){const ids=new Set(byId.get(id)?.sources||[]);D.events.forEach(e=>{if(e.child===id||e.parents.includes(id))e.sources.forEach(s=>ids.add(s))});return[...ids].map(s=>D.sources[s]).filter(Boolean)}
function detailHTML(n,mobile=false){const ps=parentsOf(n.id),cs=childrenOf(n.id),src=sourcesFor(n.id);return`${mobile?'':'<div class="detail-tag"><span>SELECTED RICE</span><span>'+ (n.year||'—') +'</span></div>'}<h3>${lang==='ja'?n.ja:n.en}</h3><span class="detail-en">${lang==='ja'?n.en:n.ja}</span><p class="detail-summary">${text(n)}</p><div class="detail-stats"><div><small>REGION</small><b>${n.region}</b></div><div><small>TYPE</small><b>${n.type.toUpperCase()}</b></div><div><small>PARENTS</small><b>${ps.length}</b></div><div><small>CHILDREN</small><b>${cs.length}</b></div></div>${ps.length?`<div class="relation-block"><span>PARENTS</span><div class="relation-links">${ps.map(id=>`<button data-detail-select="${id}">${lang==='ja'?byId.get(id).ja:byId.get(id).en}</button>`).join('')}</div></div>`:''}${cs.length?`<div class="relation-block"><span>CHILDREN</span><div class="relation-links">${cs.map(id=>`<button data-detail-select="${id}">${lang==='ja'?byId.get(id).ja:byId.get(id).en}</button>`).join('')}</div></div>`:''}<div class="source-links">${src.map(s=>`<a href="${s.url}" target="_blank" rel="noreferrer">${s.org} / ${s.title} ↗</a>`).join('')}</div>`}
function renderDetail(){const n=byId.get(selected);$('#detailPanel').innerHTML=detailHTML(n);$('#mobileDetail').innerHTML=detailHTML(n,true);$$('[data-detail-select]').forEach(b=>b.onclick=()=>setSelected(b.dataset.detailSelect))}
function renderMobile(){const n=byId.get(selected),ps=parentsOf(selected),cs=childrenOf(selected);$('#mobileYear').textContent=n.year||'YEAR —';$('#mobileRegion').textContent=n.region;$('#mobileParentCount').textContent=ps.length;$('#mobileChildCount').textContent=cs.length;$('#mobileParents').innerHTML=ps.length?ps.map(nodeButton).join(''):`<div class="empty-node">${n.type==='landrace'?(lang==='ja'?'この図では起点':'ORIGIN IN THIS MAP'):(lang==='ja'?'親系統は未表示':'PARENTS NOT SHOWN')}</div>`;$('#mobileChildren').innerHTML=cs.length?cs.map(nodeButton).join(''):`<div class="empty-node">${lang==='ja'?'v1で表示する直系の子なし':'NO DIRECT CHILD IN V1'}</div>`;$('#mobileSelected').innerHTML=`<span class="selected-label">SELECTED RICE</span><h3>${lang==='ja'?n.ja:n.en}</h3><small>${lang==='ja'?n.en:n.ja} · ${n.region}${n.year?' · '+n.year:''}</small><p>${text(n)}</p>`;$$('[data-mobile-select]').forEach(b=>b.onclick=()=>setSelected(b.dataset.mobileSelect));$('#fullMapTitle').textContent=lang==='ja'?n.ja:n.en}
function renderIndex(){const box=$('#indexGrid');box.innerHTML=D.nodes.filter(n=>n.featured).map(n=>`<a class="index-card" href="?rice=${n.id}#lineage" data-index="${[n.ja,n.en,n.region].join(' ').toLowerCase()}"><div class="index-card-top"><span>${n.region}</span><span>${n.year||'—'}</span></div><h3>${lang==='ja'?n.ja:n.en}</h3><p>${text(n)}</p></a>`).join('')}
function renderSources(){const box=$('#sourceGrid');box.innerHTML=Object.values(D.sources).map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noreferrer"><span class="source-tier">TIER ${s.tier}</span><strong>${s.org}</strong><small>${s.title}</small><span class="source-arrow">↗</span></a>`).join('')}
function renderAll(){document.body.dataset.lang=lang;renderGraph($('#lineageSvg'));renderGraph($('#fullLineageSvg'));renderDetail();renderMobile();renderIndex();renderSources()}
function search(q){q=q.trim().toLowerCase();return!q?[]:D.nodes.filter(n=>`${n.ja} ${n.en} ${n.region}`.toLowerCase().includes(q)).slice(0,10)}function renderSearch(){const input=$('#riceSearch'),out=$('#searchResults'),res=search(input.value);if(!input.value.trim()){out.hidden=true;return}out.innerHTML=res.length?res.map(n=>`<button class="search-result" data-search-select="${n.id}"><strong>${n.ja} / ${n.en}</strong><small>${n.region}</small></button>`).join(''):`<div class="search-result"><small>NO MATCH</small></div>`;out.hidden=false;$$('[data-search-select]',out).forEach(b=>b.onclick=()=>{input.value='';out.hidden=true;setSelected(b.dataset.searchSelect,{scroll:true})})}
$('#riceSearch').addEventListener('input',renderSearch);$('#searchClear').onclick=()=>{$('#riceSearch').value='';$('#searchResults').hidden=true;$('#riceSearch').focus()};document.addEventListener('click',e=>{if(!e.target.closest('.search-box'))$('#searchResults').hidden=true});
$$('[data-select-rice],[data-start-rice]').forEach(b=>b.addEventListener('click',e=>{const id=b.dataset.selectRice||b.dataset.startRice;if(id){e.preventDefault();setSelected(id,{scroll:true})}}));
$('#langToggle').onclick=()=>{lang=lang==='ja'?'en':'ja';localStorage.setItem('rice-lineage-lang',lang);renderAll()};
$('#indexSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();$$('.index-card').forEach(c=>c.hidden=!!q&&!c.dataset.index.includes(q))});
const mainSvg=$('#lineageSvg'),fullSvg=$('#fullLineageSvg');wirePanZoom(mainSvg);wirePanZoom(fullSvg,{pinch:true});$('#zoomIn').onclick=()=>zoom(mainSvg,1.15);$('#zoomOut').onclick=()=>zoom(mainSvg,.87);$('#fitMap').onclick=()=>fit(mainSvg);$('#resetMap').onclick=()=>{fit(mainSvg);setSelected(D.defaultRice)};$('#fullZoomIn').onclick=()=>zoom(fullSvg,1.15);$('#fullZoomOut').onclick=()=>zoom(fullSvg,.87);$('#fullFit').onclick=()=>fit(fullSvg);
function openFullMap(){const m=$('#fullMapModal');m.hidden=false;document.body.style.overflow='hidden';fit(fullSvg);renderGraph(fullSvg);$('#closeFullMap').focus()}function closeFullMap(){const m=$('#fullMapModal');m.hidden=true;document.body.style.overflow=''}$('#openFullMap').onclick=openFullMap;$('#closeFullMap').onclick=closeFullMap;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#fullMapModal').hidden)closeFullMap()});
renderAll();
})();