(()=>{
const N=(id,ja,en,region,year,type,featured,x,y,sj,se,sources=[])=>({id,ja,en,region,year,type,featured,x,y,summary:{ja:sj,en:se},sources});
const nodes=[
N('omachi','雄町','OMACHI','岡山',1866,'landrace',1,90,500,'岡山で選抜された古い酒米。多数の後代品種へつながる系譜上の大きな起点。','An old Okayama sake-rice variety and a major root in many later pedigrees.',['s1']),
N('tankan-wataribune','短稈渡船','TANKAN WATARIBUNE','兵庫系',null,'selection',1,300,390,'雄町から株選抜された系統で、山田錦の交配親。','A line selected from Omachi and one parent of Yamada Nishiki.',['s2']),
N('yamada-ho','山田穂','YAMADA HO','兵庫',null,'selection',1,300,270,'兵庫で純系選抜され、山田錦の交配親となった品種。','A Hyogo pure-line selection and one parent of Yamada Nishiki.',['s3']),
N('yamada-nishiki','山田錦','YAMADA NISHIKI','兵庫',1936,'cultivar',1,620,330,'山田穂と短稈渡船を1923年に交配し、1936年に認定された酒米。多くの後代へつながる大きなHub。','Bred from Yamada Ho and Tankan Wataribune in 1923 and recognized in 1936; a major pedigree hub.',['s2','s3','s4']),
N('chushi-asahi','中支旭','CHUSHI ASAHI','岡山系',null,'support',0,90,660,'菊水の交配親として系譜を支える中間ノード。','A supporting parent line of Kikusui.',['s1']),
N('kikusui','菊水','KIKUSUI','新潟系',null,'cultivar',1,360,610,'中支旭と雄町を親に持ち、五百万石へつながる。','Bred from Chushi Asahi and Omachi; later used to breed Gohyakumangoku.',['s1']),
N('shin200','新200号','SHIN 200','新潟系',null,'support',0,360,740,'五百万石の交配親として系譜に登場する育種系統。','A supporting breeding line used as a parent of Gohyakumangoku.',['s16']),
N('gohyakumangoku','五百万石','GOHYAKUMANGOKU','新潟',1957,'cultivar',1,650,650,'菊水と新200号の交配から育成された代表的な酒米。','A major sake-rice cultivar bred from Kikusui and Shin 200.',['s5','s16']),
N('koshi-tanrei','越淡麗','KOSHI TANREI','新潟',null,'cultivar',1,990,520,'山田錦と五百万石を親に持つ新潟の酒米。','A Niigata sake-rice variety bred from Yamada Nishiki and Gohyakumangoku.',['s4','s5']),
N('takane-nishiki','たかね錦','TAKANE NISHIKI','長野系',null,'cultivar',1,360,60,'美山錦の突然変異育種の起点であり、金紋錦の親でもある。','Parent line of Miyama Nishiki and one parent of Kinmon Nishiki.',['s6']),
N('miyama-nishiki','美山錦','MIYAMA NISHIKI','長野',1978,'cultivar',1,690,70,'たかね錦へのガンマ線照射による突然変異育種で生まれた酒米。','A sake-rice variety obtained through gamma-ray mutation breeding of Takane Nishiki.',['s6']),
N('kinmon-nishiki','金紋錦','KINMON NISHIKI','長野系',null,'cultivar',1,960,150,'たかね錦と山田錦を親に持つ。','Bred from Takane Nishiki and Yamada Nishiki.',['s4','s6']),
N('hattan35','八反35号','HATTAN 35','広島',null,'cultivar',1,390,860,'八反錦1号・2号につながる広島の育種系統。','A Hiroshima breeding line leading to Hattan Nishiki No.1 and No.2.',['s7','s15']),
N('akitsuho','アキツホ','AKITSUHO','広島系',null,'support',0,390,940,'八反錦1号のもう一方の交配親。','The other parent of Hattan Nishiki No.1.',['s7','s15']),
N('hattan-nishiki-1','八反錦1号','HATTAN NISHIKI NO.1','広島',1984,'cultivar',1,770,890,'八反35号とアキツホを1973年に交配し、1984年に奨励品種となった酒米。','Bred from Hattan 35 and Akitsuho in 1973 and adopted in Hiroshima in 1984.',['s7','s15']),
N('goriki','強力','GORIKI','鳥取',null,'landrace',1,120,130,'鳥取の在来種から選抜された酒米。未確認の親へは接続しない。','Selected from a Tottori local landrace; no unsupported parent is drawn.',['s8']),
N('yamayu67','山雄67','YAMAYU 67','兵庫',null,'support',0,930,350,'山田錦と雄町を親に持ち、愛山へつながる中間系統。','A breeding line from Yamada Nishiki and Omachi, later used for Aiyama.',['s4','s9']),
N('aisen117','愛船117','AISEN 117','兵庫系',null,'support',0,930,430,'愛山のもう一方の親として系譜に登場する。','The other parent of Aiyama.',['s9']),
N('aiyama','愛山','AIYAMA','兵庫',null,'cultivar',1,1240,390,'愛船117と山雄67を親に持つ。山田錦の直子ではなく、その子孫にあたる。','Bred from Aisen 117 and Yamayu 67; a descendant, not a direct child, of Yamada Nishiki.',['s9']),
N('a-kei-sake101','あ系酒101','A-KEI SAKE 101','愛知系',null,'support',0,650,770,'若水の交配親として系譜に登場する。','A supporting parent line of Wakamizu.',['s5']),
N('wakamizu','若水','WAKAMIZU','愛知系',null,'cultivar',1,930,730,'あ系酒101と五百万石を親に持ち、さがの華へつながる。','Bred from A-kei Sake 101 and Gohyakumangoku; later used for Saga no Hana.',['s5','s10']),
N('saga-no-hana','さがの華','SAGA NO HANA','佐賀',null,'cultivar',1,1260,700,'若水と山田錦を親に持つ佐賀の酒米。','A Saga sake-rice variety bred from Wakamizu and Yamada Nishiki.',['s4','s10']),
N('shiranui','シラヌイ','SHIRANUI','九州育種系',null,'support',0,900,800,'西海134号の交配親。','A supporting parent of Saikai 134.',['s4']),
N('saikai134','西海134号','SAIKAI 134','九州育種系',null,'cultivar',1,1240,800,'シラヌイと山田錦を親に持つ九州の育種系統。','A Kyushu breeding line from Shiranui and Yamada Nishiki.',['s4']),
N('89h624','89H624','89H624','九州育種系',null,'support',0,900,900,'西海222号の交配親。','A supporting parent of Saikai 222.',['s4']),
N('saikai222','西海222号','SAIKAI 222','九州育種系',null,'cultivar',1,1230,900,'山田錦と89H624を親に持ち、吟のさとの親となる。','Bred from Yamada Nishiki and 89H624 and later used as a parent of Gin no Sato.',['s4','s11']),
N('gin-no-sato','吟のさと','GIN NO SATO','九州',2007,'cultivar',1,1530,820,'山田錦と西海222号を親に持つ。九州沖縄農業研究センターで育成された酒米。','Bred from Yamada Nishiki and Saikai 222 at NARO’s Kyushu/Okinawa research center.',['s4','s11']),
N('yume-ikken','夢一献','YUME IKKEN','福岡',null,'cultivar',1,930,600,'壽限無の交配親として九州系譜に登場する。','A Fukuoka rice variety shown here as one parent of Jugemu.',['s12']),
N('jugemu','壽限無','JUGEMU','福岡',null,'cultivar',1,1270,590,'夢一献と山田錦を親に持つ福岡の酒米。','A Fukuoka sake-rice variety bred from Yume Ikken and Yamada Nishiki.',['s4','s12']),
N('yume-izumi','夢いずみ','YUME IZUMI','熊本系',null,'cultivar',1,930,510,'華錦の交配親として系譜に登場する。','Shown as one parent of Hana Nishiki.',['s13']),
N('hana-nishiki','華錦','HANA NISHIKI','熊本',null,'cultivar',1,1270,500,'夢いずみと山田錦を親に持つ熊本県オリジナルの酒造好適米。','A Kumamoto sake-rice variety bred from Yume Izumi and Yamada Nishiki.',['s4','s13']),
N('saikai62','西海62号','SAIKAI 62','九州育種系',null,'support',0,900,40,'レイホウの交配親。','A supporting parent of Reihou.',['s14']),
N('aya-nishiki','綾錦','AYA NISHIKI','九州系',null,'support',0,900,120,'レイホウのもう一方の親。','The other parent of Reihou.',['s14']),
N('reihou','レイホウ','REIHOU','九州',null,'cultivar',1,1240,80,'西海62号と綾錦を親に持つ九州系の品種。','A Kyushu rice variety bred from Saikai 62 and Aya Nishiki.',['s14'])
];
const E=(id,type,parents,child,year,sources)=>({id,type,parents,child,year,sources});
const events=[
E('e01','SELECTION',['omachi'],'tankan-wataribune',null,['s2']),
E('e02','CROSS',['yamada-ho','tankan-wataribune'],'yamada-nishiki',1923,['s2','s3']),
E('e03','CROSS',['chushi-asahi','omachi'],'kikusui',null,['s1']),
E('e04','CROSS',['kikusui','shin200'],'gohyakumangoku',1938,['s5','s16']),
E('e05','CROSS',['yamada-nishiki','gohyakumangoku'],'koshi-tanrei',null,['s4','s5']),
E('e06','MUTATION',['takane-nishiki'],'miyama-nishiki',null,['s6']),
E('e07','CROSS',['takane-nishiki','yamada-nishiki'],'kinmon-nishiki',null,['s4','s6']),
E('e08','CROSS',['hattan35','akitsuho'],'hattan-nishiki-1',1973,['s7','s15']),
E('e09','CROSS',['yamada-nishiki','omachi'],'yamayu67',null,['s4','s9']),
E('e10','CROSS',['aisen117','yamayu67'],'aiyama',null,['s9']),
E('e11','CROSS',['a-kei-sake101','gohyakumangoku'],'wakamizu',null,['s5']),
E('e12','CROSS',['wakamizu','yamada-nishiki'],'saga-no-hana',null,['s4','s10']),
E('e13','CROSS',['shiranui','yamada-nishiki'],'saikai134',null,['s4']),
E('e14','CROSS',['yamada-nishiki','89h624'],'saikai222',null,['s4','s11']),
E('e15','CROSS',['yamada-nishiki','saikai222'],'gin-no-sato',1996,['s4','s11']),
E('e16','CROSS',['yume-ikken','yamada-nishiki'],'jugemu',null,['s4','s12']),
E('e17','CROSS',['yume-izumi','yamada-nishiki'],'hana-nishiki',null,['s4','s13']),
E('e18','CROSS',['saikai62','aya-nishiki'],'reihou',null,['s14'])
];
const sources={
s1:{tier:'A',org:'岡山県',title:'「雄町」のいわれ と 酒米の系譜',url:'https://www.pref.okayama.jp/uploaded/attachment/374892.pdf'},
s2:{tier:'A',org:'酒類総合研究所',title:'原料米品種と清酒メタボロームとの関係',url:'https://www.nrib.go.jp/data/pdf/nrt/2017_1.pdf'},
s3:{tier:'A',org:'農研機構',title:'イネ品種データベース：山田穂を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=HYKE000010'},
s4:{tier:'A',org:'農研機構',title:'イネ品種データベース：山田錦を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=HYKE000070'},
s5:{tier:'A',org:'農研機構',title:'イネ品種データベース：五百万石を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=NICE000110'},
s6:{tier:'A',org:'農研機構',title:'イネ品種データベース：たかね錦を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=SKU0001900'},
s7:{tier:'A',org:'広島県',title:'水稲酒造好適米新品種「八反錦1号」「八反錦2号」の育成',url:'https://www.pref.hiroshima.lg.jp/uploaded/attachment/542318.pdf'},
s8:{tier:'A',org:'鳥取県',title:'鳥取県オリジナル酒米「強力」',url:'https://www.pref.tottori.lg.jp/291900.htm'},
s9:{tier:'A',org:'兵庫県立農林水産技術総合センター',title:'酒米試験地の設立と「山雄67号」「愛山」の育成経過',url:'https://hyogo-nourinsuisangc.jp/nourinsuisan/kenpounou/12/17/5095/'},
s10:{tier:'A',org:'農研機構',title:'イネ品種データベース：若水を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=AIC0000510'},
s11:{tier:'A',org:'農研機構',title:'イネ品種データベース：吟のさと',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=inedata_hinsyu&ineCode=SAI0002550'},
s12:{tier:'C',org:'JA全農ふくれん',title:'酒米について：壽限無',url:'https://zennoh-fukuren.jp/meshimaru/rice/sakekome.html'},
s13:{tier:'A',org:'熊本県',title:'熊本県が開発した登録品種：華錦',url:'https://www.pref.kumamoto.jp/soshiki/75/846.html'},
s14:{tier:'A',org:'農研機構',title:'イネ品種データベース：綾錦を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=AICE003640'},
s15:{tier:'A',org:'農研機構',title:'イネ品種データベース：八反35号を親にした品種一覧',url:'https://ineweb.dna.naro.go.jp/search/ine.cgi?action=oyahinsyu&ineCode=Z000001309'},
s16:{tier:'A',org:'農研機構',title:'酒米新品種「楽風舞」プレスリリース（五百万石の来歴）',url:'https://www.naro.go.jp/publicity_report/press/laboratory/carc/014007.html'}
};
window.RICE_LINEAGE_DATA={version:'1.0.0',reviewed:'2026-09-10',defaultRice:'yamada-nishiki',nodes,events,sources};
})();